// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/huipu/common/util/buff/ErrorMessage.proto

package qc.com.util;

public final class ErrorMessage {
  private ErrorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ErrorMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    boolean hasREQUEST();
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    qc.com.util.ErrorMessage.ErrorMsg.Request getREQUEST();
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder getREQUESTOrBuilder();

    // optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    boolean hasRESPONSE();
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    qc.com.util.ErrorMessage.ErrorMsg.Response getRESPONSE();
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder getRESPONSEOrBuilder();
  }
  /**
   * Protobuf type {@code com.huipu.common.util.ErrorMsg}
   */
  public static final class ErrorMsg extends
      com.google.protobuf.GeneratedMessage
      implements ErrorMsgOrBuilder {
    // Use ErrorMsg.newBuilder() to construct.
    private ErrorMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ErrorMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ErrorMsg defaultInstance;
    public static ErrorMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ErrorMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              qc.com.util.ErrorMessage.ErrorMsg.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = rEQUEST_.toBuilder();
              }
              rEQUEST_ = input.readMessage(qc.com.util.ErrorMessage.ErrorMsg.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rEQUEST_);
                rEQUEST_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              qc.com.util.ErrorMessage.ErrorMsg.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = rESPONSE_.toBuilder();
              }
              rESPONSE_ = input.readMessage(qc.com.util.ErrorMessage.ErrorMsg.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rESPONSE_);
                rESPONSE_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qc.com.util.ErrorMessage.ErrorMsg.class, qc.com.util.ErrorMessage.ErrorMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ErrorMsg> PARSER =
        new com.google.protobuf.AbstractParser<ErrorMsg>() {
      public ErrorMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMsg> getParserForType() {
      return PARSER;
    }

    public interface RequestOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code com.huipu.common.util.ErrorMsg.Request}
     *
     * <pre>
     *请求体定义
     * </pre>
     */
    public static final class Request extends
        com.google.protobuf.GeneratedMessage
        implements RequestOrBuilder {
      // Use Request.newBuilder() to construct.
      private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Request defaultInstance;
      public static Request getDefaultInstance() {
        return defaultInstance;
      }

      public Request getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Request(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qc.com.util.ErrorMessage.ErrorMsg.Request.class, qc.com.util.ErrorMessage.ErrorMsg.Request.Builder.class);
      }

      public static com.google.protobuf.Parser<Request> PARSER =
          new com.google.protobuf.AbstractParser<Request>() {
        public Request parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Request parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(qc.com.util.ErrorMessage.ErrorMsg.Request prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.huipu.common.util.ErrorMsg.Request}
       *
       * <pre>
       *请求体定义
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Request_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  qc.com.util.ErrorMessage.ErrorMsg.Request.class, qc.com.util.ErrorMessage.ErrorMsg.Request.Builder.class);
        }

        // Construct using com.huipu.common.util.ErrorMessage.ErrorMsg.Request.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor;
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Request getDefaultInstanceForType() {
          return qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance();
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Request build() {
          qc.com.util.ErrorMessage.ErrorMsg.Request result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Request buildPartial() {
          qc.com.util.ErrorMessage.ErrorMsg.Request result = new qc.com.util.ErrorMessage.ErrorMsg.Request(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof qc.com.util.ErrorMessage.ErrorMsg.Request) {
            return mergeFrom((qc.com.util.ErrorMessage.ErrorMsg.Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(qc.com.util.ErrorMessage.ErrorMsg.Request other) {
          if (other == qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          qc.com.util.ErrorMessage.ErrorMsg.Request parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (qc.com.util.ErrorMessage.ErrorMsg.Request) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.huipu.common.util.ErrorMsg.Request)
      }

      static {
        defaultInstance = new Request(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.huipu.common.util.ErrorMsg.Request)
    }

    public interface ResponseOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional bytes ERRORMSG = 1;
      /**
       * <code>optional bytes ERRORMSG = 1;</code>
       */
      boolean hasERRORMSG();
      /**
       * <code>optional bytes ERRORMSG = 1;</code>
       */
      com.google.protobuf.ByteString getERRORMSG();
    }
    /**
     * Protobuf type {@code com.huipu.common.util.ErrorMsg.Response}
     *
     * <pre>
     *响应体定义
     * </pre>
     */
    public static final class Response extends
        com.google.protobuf.GeneratedMessage
        implements ResponseOrBuilder {
      // Use Response.newBuilder() to construct.
      private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Response defaultInstance;
      public static Response getDefaultInstance() {
        return defaultInstance;
      }

      public Response getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Response(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                eRRORMSG_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qc.com.util.ErrorMessage.ErrorMsg.Response.class, qc.com.util.ErrorMessage.ErrorMsg.Response.Builder.class);
      }

      public static com.google.protobuf.Parser<Response> PARSER =
          new com.google.protobuf.AbstractParser<Response>() {
        public Response parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional bytes ERRORMSG = 1;
      public static final int ERRORMSG_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString eRRORMSG_;
      /**
       * <code>optional bytes ERRORMSG = 1;</code>
       */
      public boolean hasERRORMSG() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes ERRORMSG = 1;</code>
       */
      public com.google.protobuf.ByteString getERRORMSG() {
        return eRRORMSG_;
      }

      private void initFields() {
        eRRORMSG_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, eRRORMSG_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, eRRORMSG_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static qc.com.util.ErrorMessage.ErrorMsg.Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(qc.com.util.ErrorMessage.ErrorMsg.Response prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.huipu.common.util.ErrorMsg.Response}
       *
       * <pre>
       *响应体定义
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  qc.com.util.ErrorMessage.ErrorMsg.Response.class, qc.com.util.ErrorMessage.ErrorMsg.Response.Builder.class);
        }

        // Construct using com.huipu.common.util.ErrorMessage.ErrorMsg.Response.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          eRRORMSG_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor;
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Response getDefaultInstanceForType() {
          return qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance();
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Response build() {
          qc.com.util.ErrorMessage.ErrorMsg.Response result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public qc.com.util.ErrorMessage.ErrorMsg.Response buildPartial() {
          qc.com.util.ErrorMessage.ErrorMsg.Response result = new qc.com.util.ErrorMessage.ErrorMsg.Response(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.eRRORMSG_ = eRRORMSG_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof qc.com.util.ErrorMessage.ErrorMsg.Response) {
            return mergeFrom((qc.com.util.ErrorMessage.ErrorMsg.Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(qc.com.util.ErrorMessage.ErrorMsg.Response other) {
          if (other == qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance()) return this;
          if (other.hasERRORMSG()) {
            setERRORMSG(other.getERRORMSG());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          qc.com.util.ErrorMessage.ErrorMsg.Response parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (qc.com.util.ErrorMessage.ErrorMsg.Response) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional bytes ERRORMSG = 1;
        private com.google.protobuf.ByteString eRRORMSG_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes ERRORMSG = 1;</code>
         */
        public boolean hasERRORMSG() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bytes ERRORMSG = 1;</code>
         */
        public com.google.protobuf.ByteString getERRORMSG() {
          return eRRORMSG_;
        }
        /**
         * <code>optional bytes ERRORMSG = 1;</code>
         */
        public Builder setERRORMSG(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          eRRORMSG_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes ERRORMSG = 1;</code>
         */
        public Builder clearERRORMSG() {
          bitField0_ = (bitField0_ & ~0x00000001);
          eRRORMSG_ = getDefaultInstance().getERRORMSG();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.huipu.common.util.ErrorMsg.Response)
      }

      static {
        defaultInstance = new Response(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.huipu.common.util.ErrorMsg.Response)
    }

    private int bitField0_;
    // optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private qc.com.util.ErrorMessage.ErrorMsg.Request rEQUEST_;
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    public boolean hasREQUEST() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    public qc.com.util.ErrorMessage.ErrorMsg.Request getREQUEST() {
      return rEQUEST_;
    }
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
     */
    public qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder getREQUESTOrBuilder() {
      return rEQUEST_;
    }

    // optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;
    public static final int RESPONSE_FIELD_NUMBER = 2;
    private qc.com.util.ErrorMessage.ErrorMsg.Response rESPONSE_;
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    public boolean hasRESPONSE() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    public qc.com.util.ErrorMessage.ErrorMsg.Response getRESPONSE() {
      return rESPONSE_;
    }
    /**
     * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
     */
    public qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder getRESPONSEOrBuilder() {
      return rESPONSE_;
    }

    private void initFields() {
      rEQUEST_ = qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance();
      rESPONSE_ = qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, rEQUEST_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, rESPONSE_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rEQUEST_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rESPONSE_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static qc.com.util.ErrorMessage.ErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qc.com.util.ErrorMessage.ErrorMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.huipu.common.util.ErrorMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qc.com.util.ErrorMessage.ErrorMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qc.com.util.ErrorMessage.ErrorMsg.class, qc.com.util.ErrorMessage.ErrorMsg.Builder.class);
      }

      // Construct using com.huipu.common.util.ErrorMessage.ErrorMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getREQUESTFieldBuilder();
          getRESPONSEFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rEQUESTBuilder_ == null) {
          rEQUEST_ = qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance();
        } else {
          rEQUESTBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rESPONSEBuilder_ == null) {
          rESPONSE_ = qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance();
        } else {
          rESPONSEBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qc.com.util.ErrorMessage.internal_static_com_huipu_common_util_ErrorMsg_descriptor;
      }

      public qc.com.util.ErrorMessage.ErrorMsg getDefaultInstanceForType() {
        return qc.com.util.ErrorMessage.ErrorMsg.getDefaultInstance();
      }

      public qc.com.util.ErrorMessage.ErrorMsg build() {
        qc.com.util.ErrorMessage.ErrorMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public qc.com.util.ErrorMessage.ErrorMsg buildPartial() {
        qc.com.util.ErrorMessage.ErrorMsg result = new qc.com.util.ErrorMessage.ErrorMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (rEQUESTBuilder_ == null) {
          result.rEQUEST_ = rEQUEST_;
        } else {
          result.rEQUEST_ = rEQUESTBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (rESPONSEBuilder_ == null) {
          result.rESPONSE_ = rESPONSE_;
        } else {
          result.rESPONSE_ = rESPONSEBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qc.com.util.ErrorMessage.ErrorMsg) {
          return mergeFrom((qc.com.util.ErrorMessage.ErrorMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qc.com.util.ErrorMessage.ErrorMsg other) {
        if (other == qc.com.util.ErrorMessage.ErrorMsg.getDefaultInstance()) return this;
        if (other.hasREQUEST()) {
          mergeREQUEST(other.getREQUEST());
        }
        if (other.hasRESPONSE()) {
          mergeRESPONSE(other.getRESPONSE());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qc.com.util.ErrorMessage.ErrorMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qc.com.util.ErrorMessage.ErrorMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;
      private qc.com.util.ErrorMessage.ErrorMsg.Request rEQUEST_ = qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          qc.com.util.ErrorMessage.ErrorMsg.Request, qc.com.util.ErrorMessage.ErrorMsg.Request.Builder, qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder> rEQUESTBuilder_;
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public boolean hasREQUEST() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.Request getREQUEST() {
        if (rEQUESTBuilder_ == null) {
          return rEQUEST_;
        } else {
          return rEQUESTBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public Builder setREQUEST(qc.com.util.ErrorMessage.ErrorMsg.Request value) {
        if (rEQUESTBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rEQUEST_ = value;
          onChanged();
        } else {
          rEQUESTBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public Builder setREQUEST(
          qc.com.util.ErrorMessage.ErrorMsg.Request.Builder builderForValue) {
        if (rEQUESTBuilder_ == null) {
          rEQUEST_ = builderForValue.build();
          onChanged();
        } else {
          rEQUESTBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public Builder mergeREQUEST(qc.com.util.ErrorMessage.ErrorMsg.Request value) {
        if (rEQUESTBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              rEQUEST_ != qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance()) {
            rEQUEST_ =
              qc.com.util.ErrorMessage.ErrorMsg.Request.newBuilder(rEQUEST_).mergeFrom(value).buildPartial();
          } else {
            rEQUEST_ = value;
          }
          onChanged();
        } else {
          rEQUESTBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public Builder clearREQUEST() {
        if (rEQUESTBuilder_ == null) {
          rEQUEST_ = qc.com.util.ErrorMessage.ErrorMsg.Request.getDefaultInstance();
          onChanged();
        } else {
          rEQUESTBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.Request.Builder getREQUESTBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getREQUESTFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder getREQUESTOrBuilder() {
        if (rEQUESTBuilder_ != null) {
          return rEQUESTBuilder_.getMessageOrBuilder();
        } else {
          return rEQUEST_;
        }
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Request REQUEST = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          qc.com.util.ErrorMessage.ErrorMsg.Request, qc.com.util.ErrorMessage.ErrorMsg.Request.Builder, qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder> 
          getREQUESTFieldBuilder() {
        if (rEQUESTBuilder_ == null) {
          rEQUESTBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              qc.com.util.ErrorMessage.ErrorMsg.Request, qc.com.util.ErrorMessage.ErrorMsg.Request.Builder, qc.com.util.ErrorMessage.ErrorMsg.RequestOrBuilder>(
                  rEQUEST_,
                  getParentForChildren(),
                  isClean());
          rEQUEST_ = null;
        }
        return rEQUESTBuilder_;
      }

      // optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;
      private qc.com.util.ErrorMessage.ErrorMsg.Response rESPONSE_ = qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          qc.com.util.ErrorMessage.ErrorMsg.Response, qc.com.util.ErrorMessage.ErrorMsg.Response.Builder, qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder> rESPONSEBuilder_;
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public boolean hasRESPONSE() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.Response getRESPONSE() {
        if (rESPONSEBuilder_ == null) {
          return rESPONSE_;
        } else {
          return rESPONSEBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public Builder setRESPONSE(qc.com.util.ErrorMessage.ErrorMsg.Response value) {
        if (rESPONSEBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rESPONSE_ = value;
          onChanged();
        } else {
          rESPONSEBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public Builder setRESPONSE(
          qc.com.util.ErrorMessage.ErrorMsg.Response.Builder builderForValue) {
        if (rESPONSEBuilder_ == null) {
          rESPONSE_ = builderForValue.build();
          onChanged();
        } else {
          rESPONSEBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public Builder mergeRESPONSE(qc.com.util.ErrorMessage.ErrorMsg.Response value) {
        if (rESPONSEBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              rESPONSE_ != qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance()) {
            rESPONSE_ =
              qc.com.util.ErrorMessage.ErrorMsg.Response.newBuilder(rESPONSE_).mergeFrom(value).buildPartial();
          } else {
            rESPONSE_ = value;
          }
          onChanged();
        } else {
          rESPONSEBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public Builder clearRESPONSE() {
        if (rESPONSEBuilder_ == null) {
          rESPONSE_ = qc.com.util.ErrorMessage.ErrorMsg.Response.getDefaultInstance();
          onChanged();
        } else {
          rESPONSEBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.Response.Builder getRESPONSEBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRESPONSEFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      public qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder getRESPONSEOrBuilder() {
        if (rESPONSEBuilder_ != null) {
          return rESPONSEBuilder_.getMessageOrBuilder();
        } else {
          return rESPONSE_;
        }
      }
      /**
       * <code>optional .com.huipu.common.util.ErrorMsg.Response RESPONSE = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          qc.com.util.ErrorMessage.ErrorMsg.Response, qc.com.util.ErrorMessage.ErrorMsg.Response.Builder, qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder> 
          getRESPONSEFieldBuilder() {
        if (rESPONSEBuilder_ == null) {
          rESPONSEBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              qc.com.util.ErrorMessage.ErrorMsg.Response, qc.com.util.ErrorMessage.ErrorMsg.Response.Builder, qc.com.util.ErrorMessage.ErrorMsg.ResponseOrBuilder>(
                  rESPONSE_,
                  getParentForChildren(),
                  isClean());
          rESPONSE_ = null;
        }
        return rESPONSEBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.huipu.common.util.ErrorMsg)
    }

    static {
      defaultInstance = new ErrorMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.huipu.common.util.ErrorMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huipu_common_util_ErrorMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_huipu_common_util_ErrorMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_huipu_common_util_ErrorMsg_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_huipu_common_util_ErrorMsg_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7main/java/com/huipu/common/util/buff/E" +
      "rrorMessage.proto\022\025com.huipu.common.util" +
      "\"\251\001\n\010ErrorMsg\0228\n\007REQUEST\030\001 \001(\0132\'.com.hui" +
      "pu.common.util.ErrorMsg.Request\022:\n\010RESPO" +
      "NSE\030\002 \001(\0132(.com.huipu.common.util.ErrorM" +
      "sg.Response\032\t\n\007Request\032\034\n\010Response\022\020\n\010ER" +
      "RORMSG\030\001 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_huipu_common_util_ErrorMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_huipu_common_util_ErrorMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_huipu_common_util_ErrorMsg_descriptor,
              new java.lang.String[] { "REQUEST", "RESPONSE", });
          internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor =
            internal_static_com_huipu_common_util_ErrorMsg_descriptor.getNestedTypes().get(0);
          internal_static_com_huipu_common_util_ErrorMsg_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_huipu_common_util_ErrorMsg_Request_descriptor,
              new java.lang.String[] { });
          internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor =
            internal_static_com_huipu_common_util_ErrorMsg_descriptor.getNestedTypes().get(1);
          internal_static_com_huipu_common_util_ErrorMsg_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_huipu_common_util_ErrorMsg_Response_descriptor,
              new java.lang.String[] { "ERRORMSG", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
